# Generated by Django 3.0.3 on 2020-02-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adminlogin_Model',
            new_name='Adminlogin',
        ),
    ]
